language: java
deploy:
  provider: releases
  api_key:
    secure: JYXIimk8I1m4zIFo6Ndxxkd+29ojOCxqWOOpmlN0d9FQ6ejZ6pDPo4aGzOKqQOeDyO5dbOB4ttfheZYqSvenxF1lQ+QEkYsRoAE+rfwHxs+d9f8bU0utUHqc2b5thVKe+Vtsyn/PPOYzdN3QRQ8jjNsOdS4TCYit0XpwedRy5tA=
  file_glob: true
  file: build/libs/*
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    repo: xebialabs-community/xlr-ca-release-automation-plugin
notifications:
  hipchat:
    rooms:
      secure: HhStAYJ3Txaws4rDer5K/QMh/5L8Qkv2jxQ1F4eAeV0aq+ZcahQZMdU/gFEiiOoyKRFlp6NOgwLPqttJ+fmiWYXOYfCpkQGtBbkkS4+GJg2b7+Z11yyyaZwCl3MEnfk6OgKA/C4vyYm33wfN0Viwhnq7y1X2W2fTCPAe8CnypRM=